export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CURRENT_DEPARTMENT = "UPDATE_CURRENT_DEPARTMNET";
export const ADD_MULTIPLE_TO_PO_CART = 'ADD_MULTIPLE_TO_PO_CART';
export const ADD_TO_PO_CART = 'ADD_TO_PO_CART';
export const REMOVE_FROM_PO_CART = 'REMOVE_FROM_PO_CART';
export const UPDATE_PO_CART_QUANTITY = 'UPDATE_PO_CART_QUANTITY';
export const CLEAR_PO_CART = 'CLEAR_PO_CART';
export const UPDATE_DEPARTMENTS = "UPDATE_DEPARTMENTS";